Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2020-11, with the labels that each got.

#35 1 add dockerignore
  .dockerignore
  README.md
  connector.env
  docker-compose.yml
  pom.xml
  postgres.env
  src/main/resources/application.properties
Labels: enhancement, status:resolved

#36 33 add default policy
  CHANGELOG.md
  src/main/java/de/fraunhofer/isst/dataspaceconnector/controller/MainController.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/model/ResourceMetadata.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/services/resource/OfferedResourceServiceImpl.java
Labels: enhancement, status:resolved

#39 fix: change column definition for large objects from "BLOB" to "BYTEA"
  src/main/java/de/fraunhofer/isst/dataspaceconnector/model/OfferedResource.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/model/RequestedResource.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/model/ResourceMetadata.java
Labels: bug, status:resolved

#46 45 persist data in docker setup
  CHANGELOG.md
  docker-compose.yml
  openapi.yaml
  pom.xml
  src/main/java/de/fraunhofer/isst/dataspaceconnector/ConnectorApplication.java
  src/main/resources/conf/config.json
Labels: enhancement

#51 50 add representation name
  CHANGELOG.md
  pom.xml
  src/main/java/de/fraunhofer/isst/dataspaceconnector/model/BackendSource.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/model/ResourceRepresentation.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/services/IdsUtils.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/services/communication/ConnectorRequestServiceUtils.java
  src/test/java/de/fraunhofer/isst/dataspaceconnector/integrationtest/ArtifactRequestMessageHandlingTest.java
Labels: enhancement

#53 chore: move attribute type to BackendSource
  CHANGELOG.md
  src/main/java/de/fraunhofer/isst/dataspaceconnector/model/BackendSource.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/model/ResourceRepresentation.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/services/communication/ConnectorRequestServiceUtils.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/services/resource/OfferedResourceServiceImpl.java
  src/test/java/de/fraunhofer/isst/dataspaceconnector/integrationtest/ArtifactRequestMessageHandlingTest.java
Labels: enhancement

#56 chore: public endpoint for reduced self-description
  CHANGELOG.md
  src/main/java/de/fraunhofer/isst/dataspaceconnector/controller/MainController.java
Labels: enhancement

#57 chore: remove requested resource list from description response
  CHANGELOG.md
  src/main/java/de/fraunhofer/isst/dataspaceconnector/message/DescriptionMessageHandler.java
Labels: enhancement
