Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2021-07, with the labels that each got.

#388 fix: fix env var indentation
  charts/dataspace-connector/Chart.yaml
  charts/dataspace-connector/templates/config.yaml
  charts/dataspace-connector/templates/secret.yaml
Labels: type: bug

#392 chore: upgrade ids-messaging-services.version to 4.1.1.2
  pom.xml
Labels: type: dependencies

#393 chore: validate issuer connector on artifact request
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/services/messages/handler/ArtifactRequestHandler.java
  src/main/java/io/dataspaceconnector/services/usagecontrol/ContractManager.java
Labels: type: enhancement

#396 chore: build debug docker image
  .github/workflows/build-image.yaml
  scripts/ci/docker/Debug.dockerfile
Labels: type: maintenance

#397 fix: fix file path
  .github/workflows/build-image.yaml
Labels: type: maintenance

#398 chore: add branch tag
  .github/workflows/build-image.yaml
Labels: type: maintenance

#402 chore: increase ids messaging service version to 4.1.1.4
  CHANGELOG.md
  pom.xml
Labels: type: dependencies

#407 chore: remove redundant usages
  src/main/java/io/dataspaceconnector/camel/IdsProcessor.java
  src/main/java/io/dataspaceconnector/camel/IdsValidator.java
  src/main/java/io/dataspaceconnector/camel/event/AgreementEventHandler.java
  src/main/java/io/dataspaceconnector/config/DapsTokenValidator.java
  src/main/java/io/dataspaceconnector/service/message/handler/AbstractMessageHandler.java
  src/main/java/io/dataspaceconnector/service/message/handler/ArtifactRequestHandler.java
  src/main/java/io/dataspaceconnector/service/message/handler/ContractAgreementHandler.java
  src/main/java/io/dataspaceconnector/service/message/handler/ContractRequestHandler.java
  src/main/java/io/dataspaceconnector/service/message/handler/DescriptionRequestHandler.java
  src/main/java/io/dataspaceconnector/service/message/handler/NotificationMessageHandler.java
  src/main/java/io/dataspaceconnector/service/message/handler/ResourceUpdateMessageHandler.java
Labels: type: maintenance

#409 Update README.md
  README.md
Labels: type: documentation

#411 chore: adding links to idsg in docs
  docs/index.md
  docs/pages/deployment/configuration.md
  docs/pages/features.md
  docs/pages/getting-started.md
Labels: type: documentation

#419 refactor: move logic out of ContractRequestController
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/InvalidResponseExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/message/ContractRequestMessageController.java
  src/main/java/io/dataspaceconnector/service/ArtifactDataDownloader.java
  src/main/java/io/dataspaceconnector/service/ContractNegotiator.java
  src/main/java/io/dataspaceconnector/service/MetaDataDownloader.java
  src/main/java/io/dataspaceconnector/service/message/type/ArtifactRequestService.java
  src/main/java/io/dataspaceconnector/service/message/type/ContractAgreementService.java
  src/main/java/io/dataspaceconnector/service/message/type/ContractRequestService.java
  src/main/java/io/dataspaceconnector/service/message/type/DescriptionRequestService.java
  src/main/java/io/dataspaceconnector/service/message/type/exceptions/InvalidResponse.java
  src/main/java/io/dataspaceconnector/service/message/type/exceptions/package-info.java
  src/test/java/io/dataspaceconnector/service/message/type/exceptions/InvalidResponseTest.java
Labels: type: maintenance

#427 feat: http header as backend parameter
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/model/ArtifactDesc.java
  src/main/java/io/dataspaceconnector/model/ArtifactFactory.java
  src/main/java/io/dataspaceconnector/model/RemoteData.java
  src/main/java/io/dataspaceconnector/model/auth/ApiKey.java
  src/main/java/io/dataspaceconnector/model/auth/Authentication.java
  src/main/java/io/dataspaceconnector/model/auth/BasicAuth.java
  src/main/java/io/dataspaceconnector/model/auth/package-info.java
  src/main/java/io/dataspaceconnector/repository/AuthenticationRepository.java
  src/main/java/io/dataspaceconnector/service/HttpService.java
  src/main/java/io/dataspaceconnector/service/resource/ArtifactService.java
  src/test/java/io/dataspaceconnector/model/ArtifactFactoryTest.java
  src/test/java/io/dataspaceconnector/model/auth/ApiKeyTest.java
  src/test/java/io/dataspaceconnector/model/auth/BasicAuthTest.java
  src/test/java/io/dataspaceconnector/service/HttpServiceTest.java
  src/test/java/io/dataspaceconnector/service/resource/ArtifactServiceTest.java
Labels: type: enhancement

#455 chore: update e2e stage
  charts/dataspace-connector/Chart.yaml
  openapi.yaml
  pom.xml
  scripts/ci/e2e/active-tests.txt
  scripts/ci/e2e/setup-provider-consumer.sh
  scripts/ci/e2e/testing.sh
  scripts/ci/libraries/init.sh
  scripts/ci/libraries/libs.sh
  scripts/ci/libraries/test.sh
Labels: type: maintenance

#457 chore: drop release security scanner
  .github/workflows/build-image.yaml
Labels: type: maintenance

#458 fix: rename endpoint property of configuration
  src/main/java/io/dataspaceconnector/model/configuration/Configuration.java
  src/main/java/io/dataspaceconnector/model/configuration/ConfigurationDesc.java
  src/main/java/io/dataspaceconnector/model/configuration/ConfigurationFactory.java
  src/main/java/io/dataspaceconnector/util/IdsUtils.java
  src/main/java/io/dataspaceconnector/util/MappingUtils.java
  src/main/java/io/dataspaceconnector/view/configuration/ConfigurationView.java
  src/test/java/io/dataspaceconnector/model/configuration/ConfigurationFactoryTest.java
  src/test/java/io/dataspaceconnector/view/configuration/ConfigurationViewAssemblerTest.java
Labels: type: bug
