Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2021-03, with the labels that each got.

#161 119 offical docker image
  Dockerfile
Labels: enhancement, status:closed

#166 fix: change log filenames
  src/main/resources/log4j2.xml
Labels: bug, core-functionality, status:closed

#179 Release v4.2.0
  CHANGELOG.md
  README.md
  openapi.yaml
  pom.xml
  src/main/java/de/fraunhofer/isst/dataspaceconnector/controller/ExampleController.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/handler/ArtifactRequestHandler.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/services/usagecontrol/PolicyHandler.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/services/usagecontrol/PolicyReader.java
  src/main/java/de/fraunhofer/isst/dataspaceconnector/services/usagecontrol/PolicyVerifier.java
Labels: release

#183 feat: add action for image building
  .github/workflows/build_image.yaml
Labels: core-functionality, enhancement, status:in-progress

#197 v4.3.0
  CHANGELOG.md
  pom.xml
  src/main/java/de/fraunhofer/isst/dataspaceconnector/config/ConnectionConfiguration.java
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: release
