Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2021-09, with the labels that each got.

#545 fix: fix openapi queryinput self-reference
  CHANGELOG.md
  openapi.yaml
  src/main/java/io/dataspaceconnector/common/net/QueryInput.java
Labels: type: bug, type: documentation

#560 fix: missing noargsconstructor in BasicAuth
  src/main/java/io/dataspaceconnector/model/auth/BasicAuth.java
Labels: type: bug

#562 docs: update ids component licenses
  docs/pages/features.md
Labels: type: bug, type: docs

#566 fix: fix global exceptionhandler resolvetype
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/GlobalExceptionHandler.java
  src/main/resources/application.properties
Labels: type: bug

#582 fix: Postgres deployed when disabled
  charts/dataspace-connector/Chart.yaml
  charts/dataspace-connector/templates/certificates.yaml
  charts/dataspace-connector/templates/config.yaml
  charts/dataspace-connector/templates/configfile.yaml
  charts/dataspace-connector/templates/deployment.yaml
  charts/dataspace-connector/templates/hpa.yaml
  charts/dataspace-connector/templates/ingress.yaml
  charts/dataspace-connector/templates/secret.yaml
  charts/dataspace-connector/templates/service.yaml
  charts/dataspace-connector/templates/serviceaccount.yaml
  charts/dataspace-connector/templates/tls-certs.yaml
Labels: type: bug

#587 feat: indicator for proxy-auth-credentials
  CHANGELOG.md
  charts/dataspace-connector/Chart.yaml
  openapi.yaml
  pom.xml
  src/main/java/io/dataspaceconnector/controller/resource/view/proxy/ProxyView.java
  src/main/java/io/dataspaceconnector/controller/resource/view/proxy/ProxyViewAssembler.java
  src/test/java/io/dataspaceconnector/controller/resource/view/proxy/ProxyViewAssemblerTest.java
Labels: type: enhancement

#592 fix: check length of whole URL instead of just path
  CHANGELOG.md
  charts/dataspace-connector/Chart.yaml
  charts/dataspace-connector/templates/_helpers.tpl
  charts/dataspace-connector/templates/config.yaml
  src/main/java/io/dataspaceconnector/model/artifact/ArtifactFactory.java
Labels: type: bug

#589 fix: fix broker registration for bootstrapped resources
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/common/ids/policy/ContractUtils.java
  src/main/java/io/dataspaceconnector/common/net/SelfLinkHelper.java
  src/main/java/io/dataspaceconnector/controller/resource/view/util/SelfLinkHelper.java
  src/main/java/io/dataspaceconnector/service/EntityUpdateService.java
  src/main/java/io/dataspaceconnector/service/message/SubscriberNotificationService.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsAppRouteBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsArtifactBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsCatalogBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsConfigModelBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsContractBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsDutyBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsEndpointBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsPermissionBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsProhibitionBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsRepresentationBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsResourceBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsRouteStepBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsRuleBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/base/AbstractIdsBuilder.java
  src/main/java/io/dataspaceconnector/service/usagecontrol/DataAccessVerifier.java
  src/test/java/io/dataspaceconnector/controller/resource/view/SelfLinkHelperValueTest.java
  src/test/java/io/dataspaceconnector/service/EntityUpdateServiceTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsAppRouteBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsArtifactBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsContractBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsDutyBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsPermissionBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsProhibitionBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsRepresentationBuilderTest.java
  src/test/java/io/dataspaceconnector/service/usagecontrol/DataAccessVerifierTest.java
Labels: type: bug

#581 feat: add actuator connector status API
  CHANGELOG.md
  docs/pages/deployment/update.md
  src/main/java/io/dataspaceconnector/controller/gui/GuiController.java
  src/main/java/io/dataspaceconnector/controller/util/ResponseCode.java
  src/main/java/io/dataspaceconnector/controller/util/ResponseDescription.java
  src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
  src/main/resources/application.properties
  src/test/java/io/dataspaceconnector/controller/gui/GuiControllerTest.java
  src/test/java/io/dataspaceconnector/service/ProjectInformationServiceTest.java
  src/test/java/io/dataspaceconnector/service/appstore/portainer/PortainerRequestServiceTest.java
Labels: type: enhancement

#630 fix: create broker in DB upon bootstrap start
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/extension/bootstrap/Bootstrapper.java
Labels: type: bug

#611 release: v6.3.0
  CHANGELOG.md
  README.md
  charts/dataspace-connector/Chart.yaml
  docs/assets/images/v6/swagger_app_download.png
  docs/assets/images/v6/swagger_appstore_description.png
  docs/assets/images/v6/swagger_appstore_post.png
  docs/pages/communication.md
  docs/pages/communication/v6/camel.md
  docs/pages/communication/v6/ecosystem/appStore.md
  docs/pages/communication/v6/ecosystem/broker.md
  docs/pages/communication/v6/ecosystem/clearingHouse.md
  docs/pages/communication/v6/ecosystem/identityProvider.md
  docs/pages/deployment/build.md
  docs/pages/deployment/configuration.md
  docs/pages/deployment/update.md
  docs/pages/documentation.md
  docs/pages/documentation/v5/usage-control.md
  docs/pages/documentation/v6/usage-control.md
  openapi.yaml
  src/main/java/io/dataspaceconnector/common/exception/ErrorMessage.java
  src/main/java/io/dataspaceconnector/controller/gui/GuiController.java
  src/main/java/io/dataspaceconnector/controller/policy/util/PatternUtils.java
  src/main/java/io/dataspaceconnector/extension/monitoring/CamelInfoContributorExt.java
  src/main/java/io/dataspaceconnector/extension/monitoring/package-info.java
  src/main/java/io/dataspaceconnector/extension/monitoring/update/UpdateInfoContributor.java
  src/main/java/io/dataspaceconnector/extension/monitoring/update/UpdateInfoService.java
  src/main/java/io/dataspaceconnector/extension/monitoring/update/package-info.java
  src/main/java/io/dataspaceconnector/extension/monitoring/update/util/Repository.java
  src/main/java/io/dataspaceconnector/extension/monitoring/update/util/UpdateType.java
  src/main/java/io/dataspaceconnector/extension/monitoring/update/util/package-info.java
  src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
  src/main/resources/application.properties
  src/test/java/io/dataspaceconnector/controller/gui/GuiControllerTest.java
  src/test/java/io/dataspaceconnector/extension/monitoring/CamelInfoContributorExtTest.java
  src/test/java/io/dataspaceconnector/extension/monitoring/update/UpdateInfoContributorTest.java
  src/test/java/io/dataspaceconnector/extension/monitoring/update/UpdateInfoServiceTest.java
  src/test/java/io/dataspaceconnector/extension/monitoring/update/util/UpdateTypeTest.java
  src/test/java/io/dataspaceconnector/service/ProjectInformationServiceTest.java
Labels: type: release
