Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2021-08, with the labels that each got.

#486 chore: update vulnerable transitive dependency
  pom.xml
Labels: type: maintenance

#483 fix: fix beans not eligable for auto-proxying
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/config/DapsTokenValidator.java
Labels: scope: core-functionality, type: bug

#487 fix: restrict resource broker endpoints
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/controller/resource/BaseResourceChildRestrictedController.java
  src/main/java/io/dataspaceconnector/controller/resource/RelationControllers.java
Labels: type: bug

#498 docs: update openapi and documentation
  docs/pages/communication/v6/consumer.md
  docs/pages/communication/v6/provider.md
  openapi.yaml
Labels: type: documentation

#504 chore: bump ids messaging service to 3.1.0
  docs/pages/deployment/bootstrapping.md
  pom.xml
  src/main/java/io/dataspaceconnector/common/ids/mapping/FromIdsObjectMapper.java
  src/main/java/io/dataspaceconnector/common/ids/policy/RuleUtils.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/base/AbstractIdsBuilder.java
  src/test/java/io/dataspaceconnector/controller/policy/util/PatternUtilsTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsCatalogBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsContractBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsDutyBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsPermissionBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsProhibitionBuilderTest.java
Labels: type: maintenance

#507 feat: add resource attributes
  CHANGELOG.md
  docs/pages/communication/v6/provider.md
  src/main/java/io/dataspaceconnector/common/exception/ErrorMessage.java
  src/main/java/io/dataspaceconnector/common/ids/mapping/FromIdsObjectMapper.java
  src/main/java/io/dataspaceconnector/common/ids/mapping/ToIdsObjectMapper.java
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/JsonProcessingExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/resource/base/exceptionhandler/InvalidEntityExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/resource/view/resource/OfferedResourceView.java
  src/main/java/io/dataspaceconnector/controller/resource/view/resource/RequestedResourceView.java
  src/main/java/io/dataspaceconnector/model/resource/OfferedResourceFactory.java
  src/main/java/io/dataspaceconnector/model/resource/PaymentMethod.java
  src/main/java/io/dataspaceconnector/model/resource/RequestedResourceFactory.java
  src/main/java/io/dataspaceconnector/model/resource/Resource.java
  src/main/java/io/dataspaceconnector/model/resource/ResourceDesc.java
  src/main/java/io/dataspaceconnector/model/resource/ResourceFactory.java
  src/main/java/io/dataspaceconnector/model/subscription/SubscriptionFactory.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsResourceBuilder.java
  src/test/java/io/dataspaceconnector/common/ids/mapping/FromIdsObjectMapperTest.java
  src/test/java/io/dataspaceconnector/controller/resource/view/contract/ContractViewAssemblerTest.java
  src/test/java/io/dataspaceconnector/controller/resource/view/representation/RepresentationViewAssemblerTest.java
  src/test/java/io/dataspaceconnector/controller/resource/view/resource/OfferedResourceViewAssemblerTest.java
  src/test/java/io/dataspaceconnector/model/resource/OfferedResourceFactoryTest.java
  src/test/java/io/dataspaceconnector/model/resource/ResourceTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsCatalogBuilderTest.java
  src/test/java/io/dataspaceconnector/service/resource/ids/builder/IdsResourceBuilderTest.java
Labels: type: enhancement

#515 fix: resolve issues
  CHANGELOG.md
  openapi.yaml
  src/main/java/io/dataspaceconnector/controller/resource/type/ArtifactController.java
  src/main/java/io/dataspaceconnector/controller/resource/type/SubscriptionController.java
  src/main/java/io/dataspaceconnector/controller/resource/view/artifact/ArtifactView.java
  src/main/java/io/dataspaceconnector/controller/resource/view/contract/ContractView.java
  src/main/java/io/dataspaceconnector/controller/resource/view/representation/RepresentationView.java
  src/main/java/io/dataspaceconnector/controller/resource/view/rule/ContractRuleView.java
  src/main/java/io/dataspaceconnector/controller/resource/view/subscription/SubscriptionView.java
  src/main/java/io/dataspaceconnector/model/resource/OfferedResourceFactory.java
  src/test/java/io/dataspaceconnector/controller/resource/type/ArtifactControllerTest.java
  src/test/java/io/dataspaceconnector/model/resource/OfferedResourceFactoryTest.java
Labels: type: bug

#524 fix: add null checking for object mappers
  CHANGELOG.md
  charts/dataspace-connector/Chart.yaml
  openapi.yaml
  pom.xml
  src/main/java/io/dataspaceconnector/common/ids/mapping/FromIdsObjectMapper.java
  src/main/java/io/dataspaceconnector/common/ids/mapping/ToIdsObjectMapper.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsConfigModelBuilder.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsResourceBuilder.java
Labels: type: bug

#541 fix: load and map correct connector id
  .github/ISSUE_TEMPLATE/config.yml
  CHANGELOG.md
  README.md
  charts/dataspace-connector/Chart.yaml
  openapi.yaml
  pom.xml
  src/main/java/io/dataspaceconnector/common/ids/mapping/FromIdsObjectMapper.java
  src/main/java/io/dataspaceconnector/common/ids/mapping/ToIdsObjectMapper.java
  src/main/java/io/dataspaceconnector/controller/resource/relation/ContractsToRequestedResourcesController.java
  src/main/java/io/dataspaceconnector/controller/resource/relation/RequestedResourcesToContractsController.java
  src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsConfigModelBuilder.java
  src/main/resources/application.properties
Labels: type: enhancement
