Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2021-01, with the labels that each got.

#90 chore: Added deleted tests back. closes #89
  src/test/java/de/fraunhofer/isst/dataspaceconnector/ConnectorApplicationTests.java
  src/test/java/de/fraunhofer/isst/dataspaceconnector/UUIDUtilsTests.java
Labels: status:in-progress

#104 Workflow update
  .github/workflows/maven.yml
Labels: core-functionality, enhancement, status:in-progress

#110 107 prepare release v4.0.0
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  images/.gitkeep
  images/architecture.png
  images/artifact.PNG
  images/backend.PNG
  images/brokercommunication.PNG
  images/connector.PNG
  images/data-handshake.png
  images/description.PNG
  images/example.PNG
  images/metadata.PNG
  images/selfservice.PNG
  openapi.yaml
Labels: core-functionality, documentation, status:in-progress

#111 release v4.0.0
  CHANGELOG.md
  README.md
  openapi.yaml
  pom.xml
Labels: release

#122 Release v4.0.1
  CHANGELOG.md
  images/connector_architecture.png
  images/ids-ready.png
  images/network_architecture.png
  images/overall-architecture.png
  images/policy-negotiation-sequence.png
  openapi.yaml
  pom.xml
Labels: release
