Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2021-11, with the labels that each got.

#732 fix: add exception handling for a missing dat
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/common/exception/ErrorMessage.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/ArtifactRequestService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/ArtifactResponseService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/ContractAgreementService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/ContractRejectionService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/ContractRequestService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/DescriptionRequestService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/DescriptionResponseService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/LogMessageService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/MessageProcessedNotificationService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/NotificationService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/ProcessCreationRequestService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/SubscriptionRequestService.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/base/AbstractMessageService.java
Labels: type: bug

#731 feat: add sbom generator
  .github/workflows/build-image.yaml
  .github/workflows/ci.yml
  README.md
  dsc.pub
Labels: type: enhancement

#733 fix: fix slash in bom name
  .github/workflows/build-image.yaml
Labels: type: bug

#723 release: v6.5.1
  CHANGELOG.md
  charts/dataspace-connector/Chart.yaml
  openapi.yaml
  pom.xml
Labels: type: release

#721 fix!: remove 'settings' suffix from ConfigurationDesc attributes
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/common/ids/mapping/FromIdsObjectMapper.java
  src/main/java/io/dataspaceconnector/model/configuration/ConfigurationDesc.java
  src/main/java/io/dataspaceconnector/model/configuration/ConfigurationFactory.java
  src/main/java/io/dataspaceconnector/service/resource/type/ConfigurationService.java
  src/test/java/io/dataspaceconnector/controller/resource/view/configuration/ConfigurationViewAssemblerTest.java
  src/test/java/io/dataspaceconnector/model/configuration/ConfigurationFactoryTest.java
Labels: type: bug

#743 fix: handle SSL exception in AbstractMessageService
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/common/exception/ErrorMessage.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/base/AbstractMessageService.java
Labels: bug
