Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2021-06, with the labels that each got.

#301 297-backend-basic-auth-fails
  CHANGELOG.md
  openapi.yaml
  pom.xml
  src/main/java/io/dataspaceconnector/controller/resources/ResourceControllers.java
  src/main/java/io/dataspaceconnector/services/HttpService.java
  src/test/java/io/dataspaceconnector/services/HttpServiceTest.java
Labels: bug, core-functionality

#316 refactor: cleanup some pmd warnings
  src/main/java/io/dataspaceconnector/config/ConfigurationAdapter.java
  src/main/java/io/dataspaceconnector/config/DapsTokenMethodSecurityConfig.java
  src/main/java/io/dataspaceconnector/config/MultipleEntryPointsSecurityConfig.java
  src/main/java/io/dataspaceconnector/controller/GlobalExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/messages/ContractRequestMessageController.java
  src/main/java/io/dataspaceconnector/controller/messages/ResourceUnavailableMessageController.java
  src/main/java/io/dataspaceconnector/controller/messages/ResourceUpdateMessageController.java
  src/main/java/io/dataspaceconnector/controller/resources/BaseResourceChildController.java
  src/main/java/io/dataspaceconnector/controller/resources/BaseResourceController.java
  src/main/java/io/dataspaceconnector/model/AbstractEntity.java
  src/main/java/io/dataspaceconnector/model/Data.java
  src/main/java/io/dataspaceconnector/services/EntityResolver.java
  src/main/java/io/dataspaceconnector/services/ids/DeserializationService.java
  src/main/java/io/dataspaceconnector/services/ids/builder/AbstractIdsBuilder.java
  src/main/java/io/dataspaceconnector/services/messages/types/AbstractMessageService.java
  src/main/java/io/dataspaceconnector/services/resources/AbstractRelationService.java
  src/main/java/io/dataspaceconnector/services/resources/ArtifactService.java
  src/main/java/io/dataspaceconnector/services/resources/BaseEntityService.java
  src/main/java/io/dataspaceconnector/services/resources/NonOwningRelationService.java
  src/main/java/io/dataspaceconnector/services/usagecontrol/ContractManager.java
  src/main/java/io/dataspaceconnector/utils/TemplateUtils.java
Labels: maintenance

#324 OpenAPI schema does not match the expected response
  CHANGELOG.md
  openapi.yaml
  pom.xml
Labels: bug

#328 325-improve-test-suite
  pom.xml
  src/test/java/io/dataspaceconnector/controller/ConfigurationControllerIT.java
  src/test/java/io/dataspaceconnector/controller/ExampleControllerTest.java
  src/test/java/io/dataspaceconnector/controller/messages/DescriptionRequestMessageControllerIT.java
Labels: maintenance

#334 fix: artifact data deleted before expiration (#326)
  CHANGELOG.md
  openapi.yaml
  pom.xml
  src/main/java/io/dataspaceconnector/services/usagecontrol/RuleValidator.java
  src/main/java/io/dataspaceconnector/services/usagecontrol/ScheduledDataRemoval.java
  src/main/java/io/dataspaceconnector/utils/RuleUtils.java
  src/test/java/io/dataspaceconnector/utils/RuleUtilsTest.java
Labels: bug, core-functionality

#339 fix: cleanup duplicated tags in openapi definition
  CHANGELOG.md
  openapi.yaml
  src/main/java/io/dataspaceconnector/controller/resources/RelationControllers.java
  src/main/java/io/dataspaceconnector/controller/resources/ResourceControllers.java
  src/main/java/io/dataspaceconnector/controller/resources/tags/ResourceDescriptions.java
  src/main/java/io/dataspaceconnector/controller/resources/tags/ResourceNames.java
  src/main/java/io/dataspaceconnector/controller/resources/tags/package-info.java
Labels: bug, documentation

#341 fix: add missing paging information in openapi schema
  CHANGELOG.md
  openapi.yaml
  src/main/java/io/dataspaceconnector/controller/resources/BaseResourceChildController.java
  src/main/java/io/dataspaceconnector/controller/resources/BaseResourceController.java
  src/main/java/io/dataspaceconnector/controller/resources/MethodNotAllowedExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/resources/RelationControllers.java
  src/main/java/io/dataspaceconnector/controller/resources/ResourceControllers.java
  src/main/java/io/dataspaceconnector/controller/resources/exceptions/MethodNotAllowed.java
  src/main/java/io/dataspaceconnector/controller/resources/exceptions/package-info.java
  src/test/java/io/dataspaceconnector/controller/resources/AgreementControllerTest.java
  src/test/java/io/dataspaceconnector/controller/resources/CatalogControllerTest.java
  src/test/java/io/dataspaceconnector/controller/resources/CatalogControllerTest_getAll.java
  src/test/java/io/dataspaceconnector/controller/resources/MethodNotAllowedExceptionHandlerTest.java
  src/test/java/io/dataspaceconnector/controller/resources/RepresentationsToArtifactsTest.java
  src/test/java/io/dataspaceconnector/controller/resources/RequestedResourceControllerTest.java
Labels: bug, documentation

#344 fix: add missing toRdf to ids objects
  CHANGELOG.md
  docs/pages/documentation/usage-control.md
  src/main/java/io/dataspaceconnector/controller/ExampleController.java
  src/main/java/io/dataspaceconnector/telemetry/config/package-info.java
  src/main/java/io/dataspaceconnector/telemetry/package-info.java
Labels: bug

#348 fix: fix rule comparision
  docs/pages/documentation/usage-control.md
  scripts/tests/contract_negotation_allow_access.py
  scripts/tests/provider_consumer_multiple_artifacts.py
  scripts/tests/provider_consumer_single_artifact_multiple_policies.py
  scripts/tests/provider_consumer_single_artifact_single_policy.py
  scripts/tests/remote_data_is_unique.py
  src/main/java/io/dataspaceconnector/services/resources/AgreementService.java
  src/main/java/io/dataspaceconnector/utils/Utils.java
  src/test/java/io/dataspaceconnector/utils/RuleUtilsTest.java
Labels: bug

#351 fix: disable database autocommits
  CHANGELOG.md
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: bug, core-functionality

#352 fix: remove encoding from optional path segment
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/services/HttpService.java
Labels: bug

#356 test: fix failing tests
  src/test/java/io/dataspaceconnector/services/ids/IdsDutyBuilderTest.java
  src/test/java/io/dataspaceconnector/services/messages/handler/ResourceUpdateMessageHandlerTest.java
Labels: maintenance

#355 docs: add documentation on parametrized backend calls
  docs/pages/communication/parametrization.md
Labels: documentation

#359 chore: add image vulnerability scanner
  .github/workflows/build-image.yaml
Labels: maintenance

#366 chore: update infomodel in scripts
  docs/pages/documentation/usage-control.md
  scripts/tests/provider_consumer_multiple_artifacts.py
  scripts/tests/provider_consumer_single_artifact_multiple_policies.py
  src/main/java/io/dataspaceconnector/services/usagecontrol/RuleValidator.java
  src/main/java/io/dataspaceconnector/utils/Utils.java
Labels: maintenance

#367 chore: cleanup unused code
  src/main/java/io/dataspaceconnector/bootstrap/util/BootstrapUtils.java
  src/main/java/io/dataspaceconnector/services/resources/ArtifactService.java
  src/test/java/io/dataspaceconnector/services/messages/handler/ContractRequestHandlerTest.java
  src/test/java/io/dataspaceconnector/utils/MappingUtilsTest.java
Labels: maintenance

#369 refactor: remove basePath from ids buildern
  src/main/java/io/dataspaceconnector/services/ids/ConnectorService.java
  src/main/java/io/dataspaceconnector/services/ids/builder/AbstractIdsBuilder.java
  src/main/java/io/dataspaceconnector/services/ids/builder/IdsArtifactBuilder.java
  src/main/java/io/dataspaceconnector/services/ids/builder/IdsCatalogBuilder.java
  src/main/java/io/dataspaceconnector/services/ids/builder/IdsContractBuilder.java
  src/main/java/io/dataspaceconnector/services/ids/builder/IdsRepresentationBuilder.java
  src/main/java/io/dataspaceconnector/services/ids/builder/IdsResourceBuilder.java
  src/main/java/io/dataspaceconnector/services/ids/builder/IdsRuleBuilder.java
  src/test/java/io/dataspaceconnector/services/ids/ConnectorServiceTest.java
Labels: maintenance

#374 refactor: resolve sonarqube bugs
  src/main/java/io/dataspaceconnector/controller/messages/ContractRequestMessageController.java
  src/main/java/io/dataspaceconnector/controller/resources/BaseResourceController.java
  src/main/java/io/dataspaceconnector/services/EntityPersistenceService.java
  src/main/java/io/dataspaceconnector/services/resources/NonOwningRelationService.java
  src/main/java/io/dataspaceconnector/services/usagecontrol/PolicyExecutionService.java
Labels: maintenance
