Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2021-12, with the labels that each got.

#718 feat!: bump java version to 17
  .github/workflows/ci.yml
  CHANGELOG.md
  Dockerfile
  docs/pages/deployment/build.md
  docs/pages/getting-started.md
  pom.xml
  scripts/ci/docker/Debug.dockerfile
  scripts/ci/spotbugs-excludes.xml
  src/main/java/io/dataspaceconnector/extension/monitoring/IdsInfoContributor.java
  src/main/java/io/dataspaceconnector/service/EntityResolver.java
Labels: enhancement

#774 fix: replace builder image
  scripts/ci/docker/Debug.dockerfile
Labels: bug

#775 fix: remove dash from debug image tag
  scripts/ci/docker/Debug.dockerfile
Labels: bug

#789 chore(deps): bump log4j version from 2.14.0 to 2.15.0
  CHANGELOG.md
  pom.xml
Labels: dependencies, java

#792 fix: remove h2 version managment
  pom.xml
Labels: maintenance, dependencies, java

#797 chore(deps): bump log4j version from 2.15.0 to 2.16.0
  CHANGELOG.md
  pom.xml
Labels: dependencies, java

#735 fix!: clean up request responses
  CHANGELOG.md
  openapi.yaml
  scripts/tests/contract_negotation_count_access.py
  scripts/tests/contract_negotation_prohibit_access.py
  scripts/tests/contract_negotation_security_level_access.py
  src/main/java/io/dataspaceconnector/common/exception/UnexpectedResponseException.java
  src/main/java/io/dataspaceconnector/common/net/JsonResponse.java
  src/main/java/io/dataspaceconnector/controller/MainController.java
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/AccessDeniedExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/DataRetrievalExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/GlobalExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/JsonProcessingExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/PolicyRestrictionExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/SubscriptionProcessingExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/exceptionhandler/UnexpectedResponseExceptionHandler.java
  src/main/java/io/dataspaceconnector/controller/gui/GuiController.java
  src/main/java/io/dataspaceconnector/controller/gui/util/EnumType.java
  src/main/java/io/dataspaceconnector/controller/gui/util/GuiUtils.java
  src/main/java/io/dataspaceconnector/controller/message/AppRequestController.java
  src/main/java/io/dataspaceconnector/controller/message/NotificationController.java
  src/main/java/io/dataspaceconnector/controller/message/ids/ContractRequestMessageController.java
  src/main/java/io/dataspaceconnector/controller/message/ids/DescriptionRequestMessageController.java
  src/main/java/io/dataspaceconnector/controller/message/tag/MessageName.java
  src/main/java/io/dataspaceconnector/controller/policy/ExampleController.java
  src/main/java/io/dataspaceconnector/controller/policy/SettingsController.java
  src/main/java/io/dataspaceconnector/controller/policy/tag/PolicyName.java
  src/main/java/io/dataspaceconnector/controller/policy/tag/package-info.java
  src/main/java/io/dataspaceconnector/controller/policy/util/PatternUtils.java
  src/main/java/io/dataspaceconnector/controller/resource/base/tag/ResourceDescription.java
  src/main/java/io/dataspaceconnector/controller/resource/base/tag/ResourceName.java
  src/main/java/io/dataspaceconnector/controller/resource/type/AppController.java
  src/main/java/io/dataspaceconnector/controller/resource/type/ArtifactController.java
  src/main/java/io/dataspaceconnector/controller/resource/type/ConfigurationController.java
  src/main/java/io/dataspaceconnector/controller/resource/type/RouteController.java
  src/main/java/io/dataspaceconnector/controller/resource/type/SubscriptionController.java
  src/main/java/io/dataspaceconnector/controller/routing/BeansController.java
  src/main/java/io/dataspaceconnector/controller/routing/RoutesController.java
  src/main/java/io/dataspaceconnector/controller/routing/error/ErrorController.java
  src/main/java/io/dataspaceconnector/controller/routing/tag/CamelName.java
  src/main/java/io/dataspaceconnector/controller/util/ResponseUtils.java
  src/main/java/io/dataspaceconnector/service/message/builder/type/base/AbstractMessageService.java
  src/test/java/io/dataspaceconnector/controller/exceptionhandler/GlobalExceptionHandlerTest.java
  src/test/java/io/dataspaceconnector/controller/exceptionhandler/JsonProcessingExceptionHandlerTest.java
  src/test/java/io/dataspaceconnector/controller/exceptionhandler/PolicyRestrictionExceptionHandlerTest.java
  src/test/java/io/dataspaceconnector/controller/gui/GuiControllerTest.java
  src/test/java/io/dataspaceconnector/controller/message/ids/ConnectorUnavailableMessageControllerTest.java
  src/test/java/io/dataspaceconnector/controller/message/ids/ConnectorUpdateMessageControllerTest.java
  src/test/java/io/dataspaceconnector/controller/message/ids/QueryMessageControllerTest.java
  src/test/java/io/dataspaceconnector/controller/message/ids/ResourceUnavailableMessageControllerTest.java
  src/test/java/io/dataspaceconnector/controller/message/ids/ResourceUpdateMessageControllerBrokerTest.java
  src/test/java/io/dataspaceconnector/controller/policy/ExampleControllerIT.java
  src/test/java/io/dataspaceconnector/controller/policy/util/PatternUtilsTest.java
  src/test/java/io/dataspaceconnector/controller/routing/error/ErrorControllerTest.java
  src/test/java/io/dataspaceconnector/controller/util/ResponseUtilsTest.java
Labels: bug
