Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2022-01, with the labels that each got.

#821 fix: make database accessible
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/config/security/ConfigurationAdapter.java
  src/main/java/io/dataspaceconnector/config/security/DatabaseConsoleConfig.java
Labels: bug, core

#823 fix: add class type check to rule comparison
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/common/util/Utils.java
Labels: bug

#700 feat!: auto db migration
  CHANGELOG.md
  charts/dataspace-connector/Chart.yaml
  charts/dataspace-connector/values.yaml
  docs/pages/deployment/database-migration.md
  docs/pages/deployment/database.md
  pom.xml
  scripts/db-dumps/v5.0.0.sql
  scripts/db-dumps/v5.0.1.sql
  scripts/db-dumps/v5.0.2.sql
  scripts/db-dumps/v5.1.0.sql
  scripts/db-dumps/v5.1.1.sql
  scripts/db-dumps/v5.1.2.sql
  scripts/db-dumps/v5.2.0.sql
  scripts/db-dumps/v5.2.1.sql
  scripts/db-dumps/v6.0.0.sql
  scripts/db-dumps/v6.1.0.sql
  scripts/db-dumps/v6.1.1.sql
  scripts/db-dumps/v6.1.2.sql
  scripts/db-dumps/v6.1.3.sql
  scripts/db-dumps/v6.2.0.sql
  scripts/db-dumps/v6.3.0.sql
  scripts/db-dumps/v6.3.1.sql
  scripts/db-dumps/v6.4.0.sql
  scripts/db-dumps/v7.0.0.sql
  scripts/tests/data_request_after_migration.py
  scripts/tests/resourceapi.py
  src/main/java/db/migration/ByteaToStringColumnReplacer.java
  src/main/java/db/migration/MigrationConstants.java
  src/main/java/db/migration/V5_0_2__releaseV5_0_2.java
  src/main/java/db/migration/V5_9_9_2__releaseV6_0_0.java
  src/main/java/db/migration/V6_0_9__releaseV6_1_0.java
  src/main/java/db/migration/V6_5_0__releaseV6_5_0.java
  src/main/java/db/migration/V7_0_0__releaseV7_0_0.java
  src/main/java/db/migration/package-info.java
  src/main/java/io/dataspaceconnector/model/datasource/DataSource.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V5.0.0__Baseline.sql
  src/main/resources/db/migration/V5.1.0__releaseV5.1.0.sql
  src/main/resources/db/migration/V5.2.0__releaseV5.2.0.sql
  src/main/resources/db/migration/V5.9.9.1__releaseV6.0.0.sql
  src/main/resources/db/migration/V6.0.0__releaseV6.0.0.sql
  src/main/resources/db/migration/V6.1.0__releaseV6.1.0.sql
  src/main/resources/db/migration/V6.2.0__releaseV6.2.0.sql
  src/main/resources/db/migration/V6.4.0__releaseV6.4.0.sql
  src/main/resources/db/migration/V6.9.9__releaseV7.0.0.sql
  src/test/resources/application.properties
Labels: enhancement

#745 feat: e2e tests with routes
  .github/workflows/ci.yml
  charts/dataspace-connector/README.md
  charts/dataspace-connector/values.yaml
  charts/tests/README.md
  charts/tests/route-backend/Chart.yaml
  charts/tests/route-backend/README.md
  charts/tests/route-backend/templates/_helpers.tpl
  charts/tests/route-backend/templates/deployment.yaml
  charts/tests/route-backend/templates/service.yaml
  charts/tests/route-backend/values.yaml
  charts/tests/runner/Chart.yaml
  charts/tests/runner/README.md
  charts/tests/runner/templates/job.yaml
  charts/tests/runner/values.yaml
  pom.xml
  scripts/ci/e2e/active-tests.txt
  scripts/ci/libraries/dsc.sh
  scripts/ci/libraries/init.sh
  scripts/ci/libraries/test.sh
  scripts/tests/legacy/provider_consumer_multiple_artifacts.py
  scripts/tests/legacy/provider_consumer_single_artifact_multiple_policies.py
  scripts/tests/legacy/provider_consumer_single_artifact_single_policy.py
  scripts/tests/remote_data_is_unique.py
  scripts/tests/route-backend/backend_server.py
  scripts/tests/route-backend/requirements.txt
  scripts/tests/route-backend/route-backend.dockerfile
  scripts/tests/runner/requirements.txt
  scripts/tests/runner/runner.dockerfile
  scripts/tests/runner/scripts/contract_negotiation_allow_access.py
  scripts/tests/runner/scripts/contract_negotiation_connector_restricted_access.py
  scripts/tests/runner/scripts/contract_negotiation_count_access.py
  scripts/tests/runner/scripts/contract_negotiation_log_access.py
  scripts/tests/runner/scripts/contract_negotiation_notify_access.py
  scripts/tests/runner/scripts/contract_negotiation_prohibit_access.py
  scripts/tests/runner/scripts/contract_negotiation_security_level_access.py
  scripts/tests/runner/scripts/data_transfer_with_routes.py
  scripts/tests/runner/scripts/idsapi.py
  scripts/tests/runner/scripts/multiple_artifacts.py
  scripts/tests/runner/scripts/remote_data_can_be_updated.py
  scripts/tests/runner/scripts/remote_data_is_unique.py
  scripts/tests/runner/scripts/resourceapi.py
  scripts/tests/runner/scripts/single_artifact_multiple_policies.py
  scripts/tests/runner/scripts/subscription_creation.py
  scripts/tests/runner/scripts/subscription_with_route.py
  scripts/tests/runner/scripts/subscriptionapi.py
  todo.md
Labels: enhancement

#861 fix: add missing brackets to route templates
  CHANGELOG.md
  src/main/resources/camel-templates/app_to_app_template.ftl
  src/main/resources/camel-templates/app_to_generic_template.ftl
  src/main/resources/camel-templates/generic_to_app_template.ftl
Labels: bug
