Repository International-Data-Spaces-Association/DataspaceConnector, pull requests merged in 2022-02, with the labels that each got.

#888 fix: escape datasource url
  CHANGELOG.md
  src/main/java/io/dataspaceconnector/common/util/Utils.java
  src/main/java/io/dataspaceconnector/service/routing/BeanManager.java
  src/main/java/io/dataspaceconnector/service/routing/RouteManager.java
Labels: bug

#540 feat: Remote Attestation with CMC and tpm2d support
  .dockerignore
  CHANGELOG.md
  Dockerfile
  README.md
  charts/dataspace-connector/Chart.yaml
  docker-compose.yml
  docs/pages/deployment/configuration.md
  mvn-local/.gitignore
  mvn-local/README
  mvnw
  openapi.yaml
  pom.xml
  src/main/java/io/dataspaceconnector/common/routing/ParameterUtils.java
  src/main/java/io/dataspaceconnector/extension/idscp/config/Idscp2Config.java
  src/main/java/io/dataspaceconnector/extension/idscp/config/TypeExtractionProcessor.java
  src/main/resources/application.properties
  src/main/resources/camel-routes/handler/idscp-server.xml
  src/main/resources/log4j2.xml
  src/test/java/io/dataspaceconnector/common/routing/ParameterUtilsTest.java
  src/test/resources/application.properties
Labels: enhancement

#921 chore(deps): update chart readmes
  charts/dataspace-connector/README.md
  charts/tests/route-backend/README.md
  charts/tests/runner/README.md
Labels: docs
